services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
    ports:
      - "6002:5432"
